language: python
python:
   - "3.6"
export: PYTHONPATH=$PYTHONPATH:$(pwd)
script:
   - python -m unittest ./test/ConsumeTextText.py
   - python -m unittest ./test/FeedTextTest.py
   - python -m unittest ./test/MLAlgText.py
   - python -m unittest ./test/ProcessTextTest.py
