language: python
python: "3.6"

install: pip install unittest
export: PYTHONPATH=$PYTHONPATH:$(pwd)

script:
   - ./test/ConsumeTextText.py
   - ./test/FeedTextTest.py
   - ./test/MLAlgText.py
   - ./test/ProcessTextTest.py
