language: python
python:
   - "3.6"
install:
   - pip install unittest3

script:
   - python -m unittest ./test/ConsumeTextText.py
   - python -m unittest ./test/FeedTextTest.py
   - python -m unittest ./test/MLAlgText.py
   - python -m unittest ./test/ProcessTextTest.py
